# -*- coding: utf-8 -*-
"""AAA._Python._Decorators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N-HyCTuWcQ4SgleR7M30MQl3cpCUxD20
"""

import sys

sys.stdout.write('Hello, my friend!')

from datetime import datetime
original_write = sys.stdout.write

def my_write(string_text):
    if string_text != '\n':
      original_write(f"[{datetime.now().strftime('%Y-%m-%d %H:%m:%S')}]: {string_text}")

sys.stdout.write = my_write

print('1, 2, 3')

sys.stdout.write = original_write

def timed_output(function):
    def wrapper(*args):
      print(f"[{datetime.now().strftime('%Y-%m-%d %H:%m:%S')}]:", end=' ')
      function(*args)
    return wrapper

@timed_output
def print_greeting(name):
    print(f'Hello, {name}!')

print_greeting("Nikita")

sys.stdout.write = original_write

def redirect_output(filepath):
    def decorator(func):
      file = open(filepath, 'w')
      def wrapper():
        sys.stdout.write = file.write
        func()
      return wrapper
    return decorator

@redirect_output('/content/function_output.txt')
def calculate():
    for power in range(1, 5):
        for num in range(1, 20):
            print(num ** power, end=' ')
        print()

calculate()